In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
food_nutrition = pd.read_csv("../Data/food_nutritions/food_nutrient.csv")
food = pd.read_csv("../Data/food_nutritions/food.csv")
food_category = pd.read_csv("../Data/food_nutritions/food_category.csv")
nutrient = pd.read_csv("../Data/food_nutritions/nutrient.csv")
food_portion= pd.read_csv("../Data/food_nutritions/food_portion.csv")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_24076\2879131917.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  food_nutrition = pd.read_csv("../Data/food_nutritions/food_nutrient.csv")

In [16]:
food_nutrition.head()

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [12]:
food.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
1,319875,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
2,319876,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
3,319877,sub_sample_food,Hummus,16.0,2019-04-01
4,319878,sub_sample_food,Hummus,16.0,2019-04-01

In [13]:
food_category.head()

   id  code             description
0   1   100  Dairy and Egg Products
1   2   200        Spices and Herbs
2   3   300              Baby Foods
3   4   400           Fats and Oils
4   5   500        Poultry Products

In [14]:
nutrient.head()

     id                               name unit_name  nutrient_nbr   rank
0  2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0
2  1001                             Solids         G         201.0  200.0
3  1002                           Nitrogen         G         202.0  500.0
4  1003                            Protein         G         203.0  600.0

In [15]:
food_portion.head()

,id,fdc_id,seq_num,amount,measure_unit_id,portion_description,modifier,gram_weight,data_points,footnote,min_year_acquired
0,118702,319875.0,NaN,2.0,1001.0,NaN,NaN,35.8,1.0,NaN,NaN
1,118703,319880.0,NaN,2.0,1001.0,NaN,NaN,36.2,1.0,NaN,NaN
2,118704,319881.0,NaN,2.0,1001.0,NaN,NaN,33.4,1.0,NaN,NaN
3,118705,319886.0,NaN,2.0,1001.0,NaN,NaN,33.2,1.0,NaN,NaN
4,118706,319889.0,NaN,2.0,1001.0,NaN,NaN,34.6,1.0,NaN,NaN

In [17]:
nutrition_df=food_nutrition.merge(
    nutrient,
    left_on='nutrient_id',
    right_on='id',
    how='left'
)

In [18]:
nutrition_df.head()

,id_x,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,id_y,name,unit_name,nutrient_nbr,rank
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1051.0,Water,G,255.0,100.0
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1002.0,Nitrogen,G,202.0,500.0
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1004.0,Total lipid (fat),G,204.0,800.0
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1007.0,Ash,G,207.0,1000.0
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1091.0,"Phosphorus, P",MG,305.0,5600.0

In [19]:
df2=nutrition_df.merge(
    food,
    on='fdc_id',
    how='left'
)

In [20]:
df2.head()

,id_x,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,id_y,name,unit_name,nutrient_nbr,rank,data_type,description,food_category_id,publication_date
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1051.0,Water,G,255.0,100.0,sub_sample_food,Hummus,16.0,2019-04-01
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1002.0,Nitrogen,G,202.0,500.0,sub_sample_food,Hummus,16.0,2019-04-01
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1004.0,Total lipid (fat),G,204.0,800.0,sub_sample_food,Hummus,16.0,2019-04-01
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1007.0,Ash,G,207.0,1000.0,sub_sample_food,Hummus,16.0,2019-04-01
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1091.0,"Phosphorus, P",MG,305.0,5600.0,sub_sample_food,Hummus,16.0,2019-04-01

In [21]:
df2['name'].unique()

array(['Water', 'Nitrogen', 'Total lipid (fat)', 'Ash', 'Phosphorus, P',
       'Manganese, Mn', 'Potassium, K', 'Calcium, Ca', 'Sodium, Na',
       'Magnesium, Mg', 'Iron, Fe', 'Copper, Cu', 'Zinc, Zn',
       'Pantothenic acid', 'SFA 14:0', 'SFA 24:0', 'SFA 11:0', 'SFA 18:0',
       'PUFA 22:6 n-3 (DHA)', 'SFA 6:0', 'PUFA 22:4', 'SFA 15:0',
       'PUFA 20:5 n-3 (EPA)', 'PUFA 18:2 CLAs', 'PUFA 20:4', 'SFA 4:0',
       'SFA 16:0', 'TFA 16:1 t', 'PUFA 18:4', 'SFA 22:0',
       'PUFA 22:5 n-3 (DPA)', 'TFA 18:1 t', 'PUFA 20:3 n-9', 'MUFA 15:1',
       'MUFA 18:1 c', 'MUFA 20:1 c', 'PUFA 18:3 n-3 c,c,c (ALA)',
       'SFA 20:0', 'TFA 22:1 t', 'PUFA 22:2', 'PUFA 20:2 n-6 c,c',
       'MUFA 22:1 n-9', 'SFA 10:0', 'SFA 17:0', 'SFA 12:0', 'SFA 8:0',
       'TFA 18:2 t not further defined', 'MUFA 16:1 c', 'PUFA 20:3 n-6',
       'TFA 18:3 t', 'PUFA 18:3 n-6 c,c,c', 'PUFA 18:2 n-6 c,c',
       'MUFA 14:1 c', 'MUFA 17:1', 'MUFA 24:1 c', 'PUFA 20:3 n-3',
       'Starch', 'Folate, total', 'Selenium, Se', 'Riboflavin', 'Niacin',
       'Fiber, total dietary', 'Thiamin', 'Vitamin B-6',
       'Lutein + zeaxanthin', 'Carotene, beta', 'Cryptoxanthin, beta',
       'Lycopene', 'Carotene, alpha', 'Tocopherol, delta',
       'Tocopherol, beta', 'Tocopherol, gamma',
       'Vitamin E (alpha-tocopherol)', 'Tocotrienol, alpha',
       'Tocotrienol, beta', 'Tocotrienol, gamma', 'Tocotrienol, delta',
       'Vitamin C, total ascorbic acid', 'Lactose', 'Glucose', 'Sucrose',
       'Maltose', 'Galactose', 'Fructose', 'Vitamin K (Menaquinone-4)',
       'Vitamin K (Dihydrophylloquinone)', 'Vitamin K (phylloquinone)',
       'Choline, from glycerophosphocholine', 'Betaine',
       'Choline, from phosphocholine',
       'Choline, from phosphotidyl choline', 'Choline, free',
       'Choline, total', 'Choline, from sphingomyelin',
       'Vitamin D2 (ergocalciferol)', '25-hydroxycholecalciferol',
       'Vitamin D3 (cholecalciferol)', 'Cholesterol', 'Iodine, I',
       'SFA 21:0', 'SFA 9:0', 'SFA 7:0', 'MUFA 22:1 n-11', 'PUFA 22:3',
       'Fatty acids, total trans', 'SFA 23:0', 'TFA 14:1 t',
       'Fatty acids, total monounsaturated',
       'Fatty acids, total polyunsaturated', 'TFA 20:1 t', 'MUFA 12:1',
       'SFA 5:0', 'Fatty acids, total saturated', 'Serine', 'Valine',
       'Leucine', 'Arginine', 'Glutamic acid', 'Alanine', 'Cysteine',
       'Histidine', 'Hydroxyproline', 'Phenylalanine', 'Aspartic acid',
       'Isoleucine', 'Proline', 'Tryptophan', 'Threonine', 'Glycine',
       'Methionine', 'Tyrosine', 'Lysine', 'Vitamin B-12', 'Retinol',
       'Zeaxanthin', 'trans-beta-Carotene', 'trans-Lycopene', 'Lutein',
       'cis-beta-Carotene', 'cis-Lycopene', 'Cryptoxanthin, alpha',
       'cis-Lutein/Zeaxanthin', 'Protein', 'MUFA 20:1',
       'Fatty acids, total trans-dienoic', 'Total fat (NLEA)',
       'Fatty acids, total trans-monoenoic', 'Energy',
       'Carbohydrate, by summation', 'PUFA 20:2 c', 'Vitamin A, RAE',
       'Sugars, Total', 'PUFA 20:3 c', 'PUFA 22:5 c', 'MUFA 17:1 c',
       'Fatty acids, total trans-polyenoic', 'PUFA 18:2 c', 'PUFA 18:3 c',
       'PUFA 20:5c', 'PUFA 22:6 c', 'Carbohydrate, by difference',
       'PUFA 20:4c', 'MUFA 22:1 c', 'Energy (Atwater General Factors)',
       'Energy (Atwater Specific Factors)', 'Vitamin D (D2 + D3)',
       'Vitamin D (D2 + D3), International Units', nan, 'Phytofluene',
       'Phytoene', 'Fiber, insoluble', 'Fiber, soluble', 'Cystine',
       'MUFA 18:1', 'PUFA 18:2', 'PUFA 20:3', 'PUFA 18:3', 'PUFA 18:3i',
       'Specific Gravity', 'MUFA 22:1',
       '5-Formyltetrahydrofolic acid (5-HCOH4',
       '10-Formyl folic acid (10HCOFA)',
       '5-methyl tetrahydrofolate (5-MTHF)', 'Molybdenum, Mo',
       'Sulfur, S', 'Cobalt, Co', 'Boron, B', 'Nickel, Ni', 'Biotin',
       'Beta-sitostanol', 'Campesterol', 'Campestanol',
       'Phytosterols, other', 'Beta-sitosterol', 'Brassicasterol',
       'Delta-5-avenasterol', 'Stigmasterol',
       'Total dietary fiber (AOAC 2011.25)', 'Malic acid', 'Citric acid',
       'TFA 18:2 t', 'Genistin', 'Daidzein', 'Genistein', 'Glycitin',
       'Daidzin', 'Carotene, gamma', 'Total Sugars', 'Stigmastadiene',
       'Delta-7-Stigmastenol', 'Glutathione', 'Beta-glucan',
       'Ergosta-7,22-dienol', 'Ergosterol', 'Vitamin D4',
       'Ergosta-7-enol', 'Ergosta-5,7-dienol', 'Ergothioneine',
       'Raffinose', 'Stachyose', 'Verbascose', 'Oxalic acid',
       'Quinic acid', 'High Molecular Weight Dietary Fiber (HMWDF)',
       'Low Molecular Weight Dietary Fiber (LMWDF)', 'Pyruvic acid',
       'Resistant starch', 'MUFA 14:1', 'MUFA 16:1', 'Vitamin E',
       'PUFA 20:4 n-3', 'SFA 13:0', 'PUFA 20:4 n-6',
       'MUFA 18:1-11 c (18:1c n-7)'], dtype=object)

In [27]:
# Select only the important nutrients that actually affect health
important_nutrients = [
    "Protein",
    "Total lipid (fat)",
    "Carbohydrate, by difference",
    "Total Sugars",
    "Fiber, total dietary",
    "Sodium, Na",
    "Potassium, K",
    "Cholesterol",
    "Energy",
    "Vitamin C, total ascorbic acid",
    "Calcium, Ca",
    "Iron, Fe"
]

df_nutrients=df2[df2['name'].isin(important_nutrients)]

In [28]:
df = df_nutrients[
    [
        "description",
        "name",
        "amount",
        "food_category_id"
    ]
]

In [29]:
df.head()

   description               name  amount  food_category_id
2       Hummus  Total lipid (fat)   19.00              16.0
6       Hummus       Potassium, K  326.00              16.0
7       Hummus        Calcium, Ca   46.00              16.0
8       Hummus         Sodium, Na  446.00              16.0
10      Hummus           Iron, Fe    2.33              16.0

In [30]:
final_df=df.pivot_table(
    index='description',
    columns='name',
    values='amount',
    aggfunc='mean'
).reset_index()

In [31]:
final_df.head()

name,description,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na",Total Sugars,Total lipid (fat),"Vitamin C, total ascorbic acid"
0,Egg whites,8.600000,NaN,NaN,NaN,NaN,0.185000,129.937500,NaN,143.937500,NaN,NaN,NaN
1,"Egg whites, dried",104.333333,NaN,NaN,NaN,NaN,0.000000,958.733333,NaN,1250.666667,NaN,NaN,NaN
2,Egg yolk,119.333333,NaN,NaN,NaN,NaN,4.128000,102.466667,NaN,65.866667,NaN,NaN,NaN
3,"Egg yolks, dried",274.444444,NaN,NaN,NaN,NaN,9.301111,230.777778,NaN,146.888889,NaN,NaN,NaN
4,Whole eggs,54.928571,NaN,NaN,NaN,NaN,1.770714,116.642857,NaN,121.428571,NaN,NaN,NaN

In [32]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3454 entries, 0 to 3453
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   description                     3454 non-null   object
 1   Calcium, Ca                     2042 non-null   float64
 2   Carbohydrate, by difference     328 non-null    float64
 3   Cholesterol                     396 non-null    float64
 4   Energy                          107 non-null    float64
 5   Fiber, total dietary            1302 non-null   float64
 6   Iron, Fe                        2037 non-null   float64
 7   Potassium, K                    2030 non-null   float64
 8   Protein                         1321 non-null   float64
 9   Sodium, Na                      1198 non-null   float64
 10  Total Sugars                    10 non-null     float64
 11  Total lipid (fat)               2220 non-null   float64
 12  Vitamin C, total ascorbic acid  337 non-null    float64
dtypes: float64(12), object(1)
memory usage: 350.9+ KB